import express from 'express'
import bcrypt from 'bcryptjs'
import jwt from 'jsonwebtoken'
import db from '../db.js'

const router = express.Router()

router.post('/register', (req,res) => {
    const { username,password } = req.body //to get the body of incoming request

    //encrypt the password using bcrypt
    const hashedPassword = bcrypt.hashSync(password, 8)
    
    //save the new user into the database
    try{
        //run sql queries so use prepare method
        //this will prepare the db for new user and insert new user into the users table
        const newUser = db.prepare(`INSERT INTO users (username, password)
            VALUES (?, ?)`) //values(?,?) indicates that the values will be provided later, and the ? is a placeholder for the values that will be provided later
            const result = newUser.run(username, hashedPassword)

            //give a default todo new user
            const defaultTodo = `Hello! Add your first todo`
            const insertTodo = db.prepare(`INSERT INTO todos (user_id, task) 
                VALUES (?, ?)`)  //id and boolean completed will be automatically generated by the database, so we only need to provide the user_id and task values
                insertTodo.run(result.lastInsertRowid, defaultTodo) //lastInserRowid means id of most recent added user

            //generate a jwt token for the new user
            const token = jwt.sign({ id: result.lastInsertRowid}, process.env.JWT_SECRET, { expiresIn: '24h' })
            res.json({ token }) //send the token back to the client

    } catch(err){
        console.log(err.message)
        res.sendStatus(503)
    }



    
    

})

router.post('/login', (req,res) => {
    const { username, password } = req.body
    try{
        const getUser = db.prepare(`SELECT * FROM users WHERE username=?`) //SELECT * reads the whole users table and finds the column for username
        const user = getUser.get(username)

        if(!user){return res.status(404).send({ message: "User not found"})}

        const passwordIsValid = bcrypt.compareSync(password, user.password)

        if(!passwordIsValid){return res.status(401).send({ message: 'Invalid Password' })}

        const token = jwt.sign({ id: user.id}, process.env.JWT_SECRET, { expiresIn: '24h'})
        res.json({ token })

    } catch(err){
        console.log(err.message)
        res.sendStatus(503)
    }
    
})

export default router